package com.ldg.api.po;

public class Book {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book.isbn
	 * @mbggenerated
	 */
	private Integer isbn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book.book_name
	 * @mbggenerated
	 */
	private String bookName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book.price
	 * @mbggenerated
	 */
	private Double price;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book.isbn
	 * @return  the value of book.isbn
	 * @mbggenerated
	 */
	public Integer getIsbn() {
		return isbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book.isbn
	 * @param isbn  the value for book.isbn
	 * @mbggenerated
	 */
	public void setIsbn(Integer isbn) {
		this.isbn = isbn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book.book_name
	 * @return  the value of book.book_name
	 * @mbggenerated
	 */
	public String getBookName() {
		return bookName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book.book_name
	 * @param bookName  the value for book.book_name
	 * @mbggenerated
	 */
	public void setBookName(String bookName) {
		this.bookName = bookName == null ? null : bookName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book.price
	 * @return  the value of book.price
	 * @mbggenerated
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book.price
	 * @param price  the value for book.price
	 * @mbggenerated
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	@Override
	public String toString() {
		return "Book [isbn=" + isbn + ", bookName=" + bookName + ", price=" + price + "]";
	}
	
}