package com.ldg.impl.mapper;

import com.ldg.api.po.Book;

public interface BookMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer isbn);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book
	 * @mbggenerated
	 */
	int insert(Book record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book
	 * @mbggenerated
	 */
	int insertSelective(Book record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book
	 * @mbggenerated
	 */
	Book selectByPrimaryKey(Integer isbn);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Book record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table book
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Book record);
}